/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF, Float } from '@react-three/drei'
import {useFrame } from "@react-three/fiber"

export function ModelSzerszen({position, scale}) {

  const { nodes, materials } = useGLTF('/3d/szerszen.glb')
  const ref = useRef()

  useFrame((state) => {
    const t = state.clock.getElapsedTime()
    //ref.current.rotation.z = -0.2 - (1 + Math.sin(t * 30)/20)
    //ref.current.rotation.y = Math.sin(t / 0.3)
  })


  return (
    <group 
    position={position} 
    scale={scale}
    ref={ref}  
    dispose={null}>
      <mesh geometry={nodes.mesh_0.geometry}>
      
        <meshPhysicalMaterial 
        color='gray'
        clearcoat={1}
        clearcoatRoughness={1}
        roughness={0}
        metalness={1}
        reflectivity={1}
        emissive="red"
        emissiveIntensity={0.02}
        />
      </mesh>

    </group>
  )
}

useGLTF.preload('/3d/szerszen.glb')
