/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function ModelNoise(props) {
  const { nodes, materials } = useGLTF(process.env.PUBLIC_URL + '/3d/noise.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.mesh_0.geometry}>
      <meshPhysicalMaterial 
      color='black'
      clearcoat={1}
      clearcoatRoughness={.7}
      roughness={.6}
      metalness={.2}
      reflectivity={.1}
      />
      </mesh>
    </group>
  )
}

useGLTF.preload(process.env.PUBLIC_URL + '/3d/noise.glb')
